---@module nvim-float.style_editor.persistence
---Persistence for style overrides - saves and loads highlight customizations

local M = {}

---Get the persistence file path
---@return string
local function get_persistence_file()
  return vim.fn.stdpath("data") .. "/nvim_float_style.lua"
end

---Serialize a table to Lua code
---@param tbl table The table to serialize
---@param indent number Current indentation level
---@return string
local function serialize_table(tbl, indent)
  indent = indent or 0
  local pad = string.rep("  ", indent)
  local pad_inner = string.rep("  ", indent + 1)

  local parts = { "{\n" }

  -- Sort keys for consistent output
  local keys = {}
  for k in pairs(tbl) do
    table.insert(keys, k)
  end
  table.sort(keys)

  for _, k in ipairs(keys) do
    local v = tbl[k]
    local key_str

    -- Handle key formatting
    if type(k) == "string" and k:match("^[%a_][%w_]*$") then
      key_str = k
    else
      key_str = string.format("[%q]", k)
    end

    -- Handle value formatting
    local val_str
    if type(v) == "table" then
      val_str = serialize_table(v, indent + 1)
    elseif type(v) == "string" then
      val_str = string.format("%q", v)
    elseif type(v) == "number" then
      -- Format colors as hex strings for readability
      if k == "fg" or k == "bg" then
        val_str = string.format('"#%06X"', v)
      else
        val_str = tostring(v)
      end
    elseif type(v) == "boolean" then
      val_str = tostring(v)
    else
      val_str = string.format("%q", tostring(v))
    end

    table.insert(parts, string.format("%s%s = %s,\n", pad_inner, key_str, val_str))
  end

  table.insert(parts, pad .. "}")
  return table.concat(parts)
end

---Load persisted style overrides from disk
---@return table<string, table>? overrides The saved overrides or nil if none
function M.load()
  local filepath = get_persistence_file()

  if vim.fn.filereadable(filepath) ~= 1 then
    return nil
  end

  -- Load the Lua file
  local ok, result = pcall(dofile, filepath)
  if not ok then
    vim.notify("nvim-float: Failed to load style overrides: " .. tostring(result), vim.log.levels.WARN)
    return nil
  end

  if type(result) ~= "table" then
    return nil
  end

  return result
end

---Save style overrides to disk
---@param overrides table<string, table> The highlight overrides to save
---@return boolean success
function M.save(overrides)
  local filepath = get_persistence_file()

  -- Build the Lua file content
  local content = string.format(
    [[-- nvim-float style overrides
-- Auto-generated by nvim-float Style Editor
-- Location: %s

return %s
]],
    filepath,
    serialize_table(overrides, 0)
  )

  -- Write to file
  local file, err = io.open(filepath, "w")
  if not file then
    vim.notify("nvim-float: Failed to save style overrides: " .. tostring(err), vim.log.levels.ERROR)
    return false
  end

  file:write(content)
  file:close()

  return true
end

---Clear persisted style overrides
---@return boolean success
function M.clear()
  local filepath = get_persistence_file()

  if vim.fn.filereadable(filepath) ~= 1 then
    return true -- Already cleared
  end

  local ok, err = os.remove(filepath)
  if not ok then
    vim.notify("nvim-float: Failed to clear style overrides: " .. tostring(err), vim.log.levels.WARN)
    return false
  end

  return true
end

---Check if there are persisted overrides
---@return boolean
function M.has_overrides()
  local filepath = get_persistence_file()
  return vim.fn.filereadable(filepath) == 1
end

---Get the persistence file path (for user reference)
---@return string
function M.get_file_path()
  return get_persistence_file()
end

return M
